// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("limitbreak")>]
[<assembly: AssemblyProductAttribute("limitbreak")>]
[<assembly: AssemblyDescriptionAttribute("Functions for tracking event frequency and applying rate limits.")>]
[<assembly: AssemblyVersionAttribute("0.0.5")>]
[<assembly: AssemblyFileVersionAttribute("0.0.5")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "limitbreak"
    let [<Literal>] AssemblyProduct = "limitbreak"
    let [<Literal>] AssemblyDescription = "Functions for tracking event frequency and applying rate limits."
    let [<Literal>] AssemblyVersion = "0.0.5"
    let [<Literal>] AssemblyFileVersion = "0.0.5"
    let [<Literal>] AssemblyConfiguration = "Release"
